name: Release New AGLAE Converter
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build nuitka packages
    uses: ./.github/workflows/build-package.yml

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
          path: ./

      - name: Download windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-binary
          path: ./

      - name: Compute tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.compute_tag.outputs.next_tag }}
          title: "Development Build"
          files: |
            converter-win.exe
            converter-linux
