name: Release New AGLAE Converter
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build nuitka packages
    uses: ./.github/workflows/build-package.yml

  release:
    needs: [install-linux, install-win]
    runs-on: ubuntu-latest
    steps:
      - name: Download linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
          path: ./

      - name: Download windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-binary
          path: ./

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Development Build"
          files: |
            converter-win.exe
            converter-linux
