name: Test Converter Function
on: workflow_call

permissions:
  contents: read

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.2.2-0

      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Download hdf5
        run: |
          sudo apt-get install -y hdf5-tools libhdf5-dev

      - name: Run rust test
        run: cargo test

  hdf5-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.2.2-0

      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Download hdf5
        run: |
          sudo apt-get install -y hdf5-tools libhdf5-dev

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Install project
        run: poetry install --no-interaction

      - name: Build Lstrs
        run: make build_rs

      - name: Run Converter Function
        run: |
          poetry run python new_aglae_data_converter/converter.py --extraction-types standards lst globals --data-path ./test_assets/data --output-path . --log=DEBUG

      - name: Save HDF5
        uses: actions/upload-artifact@v3
        with:
          name: hdf5
          path: |
            *.hdf5

      - name: Compare Standard & Globals HDF5 Files
        run: |
          h5diff std.hdf5 ./test_assets/out/std.hdf5
          h5diff globals.hdf5 ./test_assets/out/globals.hdf5

      - name: Compare LST HDF5 Files
        run: |
          h5diff 20230227_0002_Std_SASHI_IBA.hdf5 ./test_assets/out/20230227_0002_Std_SASHI_IBA.hdf5
          h5diff 20230510_0001_Std_COLORSOURCES_IBA.hdf5 ./test_assets/out/20230510_0001_Std_COLORSOURCES_IBA.hdf5
